import { Inter } from "next/font/google";
import "./globals.css";
import { FirebaseProvider } from "@/features/FirebaseContext"; // Update this import

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
        <FirebaseProvider> {/* Use FirebaseProvider here */}
          {children}
        </FirebaseProvider>
      </body>
    </html>
  );
}
